# -*- coding: utf-8 -*-
"""naverapi

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xk6qUn_eYonjikw2Hb1ncA-TVs2UQEcy
"""

import os
import sys
import urllib.request
import json

client_id = "Ey5m8LgneWoCTPofCLJs"
client_secret = "Be0LOzgfuV"
encText = urllib.parse.quote("성산일출봉")
url = "https://openapi.naver.com/v1/search/image?display=100&query=" + encText + " 인생샷"

request = urllib.request.Request(url)
request.add_header("X-Naver-Client-Id",client_id)
request.add_header("X-Naver-Client-Secret",client_secret)
response = urllib.request.urlopen(request)
rescode = response.getcode()

# 이미지 저장 경로
savePath = "/content/naverapi/"

if(rescode==200):
    response_body = response.read()
    result = json.loads(response_body)
    img_list = result['items']
    print(result)
  

    for i, img_list in enumerate(img_list, 1):
        
        # 이미지링크 확인
        print(img_list['link'])

        # 저장 파일명 및 경로
        FileName = os.path.join(savePath, savePath + str(i) + '.jpg')
        
        # 파일명 출력 
        print('full name : {}'.format(FileName))
        
        # 이미지 다운로드 URL 요청
        urllib.request.urlretrieve(img_list['link'], FileName)

    # 다운로드 완료 시 출력
    print("--------download succeeded--------")

else:
    print("Error Code:" + rescode)

